include:
  - project: tremorvideodsp/dspsharedlibrary
    ref: master
    file: /gitlab-ci/base/sbt.yml

variables:
  CPU: 8
  RAM: 8000Mi
  IAD1_PROD_PODS: 2
  EU1_PROD_PODS: 2
  AP1_PROD_PODS: 2
  JAVA_VERSION: 13
  CANARY_PODS: 1

### temporary until dspsharedlibrary fix is in
test:
  stage: build
  image: tremorvideo/centos-jdk15:latest
  variables:
    NAMESPACE: budgeter
  #  services:
  #    - name: aerospike/aerospike-server
  #      alias: aerospike
  script:
    - curl https://bintray.com/sbt/rpm/rpm |  tee /etc/yum.repos.d/bintray-sbt-rpm.repo
    - yum install -y git java-1.8.0-openjdk sbt
    - sbt clean test -J-XX:MaxMetaspaceSize=512m ### add it:test after first deploy
  allow_failure: false

artifact:
  stage: build
  image: tremorvideo/centos-jdk15:latest
  script:
    - curl https://bintray.com/sbt/rpm/rpm |  tee /etc/yum.repos.d/bintray-sbt-rpm.repo
    - yum install -y git java-1.8.0-openjdk sbt
    - sbt universal:packageZipTarball
  artifacts:
    expire_in: 1 week
    paths:
      - target/universal
  allow_failure: false