include:
  - project: tremorvideodsp/dspsharedlibrary
    ref: master
    file: /gitlab-ci/base/sbt.yml

variables:
  CPU: 8
  RAM: 8000Mi
  IAD1_PROD_PODS: 2
  EU1_PROD_PODS: 2
  AP1_PROD_PODS: 2
  JAVA_VERSION: 13
  CANARY_PODS: 1

### temporary until dspsharedlibrary fix is in
test:
  stage: build
  image: tremorvideo/centos-jdk15:latest
  variables:
    NAMESPACE: budgeter
  #  services:
  #    - name: aerospike/aerospike-server
  #      alias: aerospike
  script:
    - curl https://bintray.com/sbt/rpm/rpm |  tee /etc/yum.repos.d/bintray-sbt-rpm.repo
    - yum install -y git java-1.8.0-openjdk sbt
    - sbt clean test -J-XX:MaxMetaspaceSize=512m ### add it:test after first deploy
  allow_failure: false

artifact:
  stage: build
  image: tremorvideo/centos-jdk15:latest
  script:
    - curl https://bintray.com/sbt/rpm/rpm |  tee /etc/yum.repos.d/bintray-sbt-rpm.repo
    - yum install -y git java-1.8.0-openjdk sbt
    - sbt universal:packageZipTarball
  artifacts:
    expire_in: 1 week
    paths:
      - target/universal
  allow_failure: false

iad1-canary test:
  stage: iad1
  image: tremorvideo/centos-jdk15:latest
  variables:
    NAMESPACE: $name$
  script:
    - curl https://bintray.com/sbt/rpm/rpm |  tee /etc/yum.repos.d/bintray-sbt-rpm.repo
    - yum install -y git java-1.8.0-openjdk sbt
    - sbt "it:testOnly * -- -Ddc=iad1 -Denv=canary" -J-XX:MaxMetaspaceSize=512m
  allow_failure: true
  when: manual

iad1-prod test:
  stage: iad1
  image: tremorvideo/centos-jdk15:latest
  variables:
    NAMESPACE: $name$
  script:
    - curl https://bintray.com/sbt/rpm/rpm |  tee /etc/yum.repos.d/bintray-sbt-rpm.repo
    - yum install -y git java-1.8.0-openjdk sbt
    - sbt "it:testOnly * -- -Ddc=iad1 -Denv=prod" -J-XX:MaxMetaspaceSize=512m
  allow_failure: true
  when: manual

eu1-canary test:
  stage: eu1
  image: tremorvideo/centos-jdk15:latest
  variables:
    NAMESPACE: $name$
  script:
    - curl https://bintray.com/sbt/rpm/rpm |  tee /etc/yum.repos.d/bintray-sbt-rpm.repo
    - yum install -y git java-1.8.0-openjdk sbt
    - sbt "it:testOnly * -- -Ddc=eu1 -Denv=canary" -J-XX:MaxMetaspaceSize=512m
  allow_failure: true
  when: manual

eu1-prod test:
  stage: eu1
  image: tremorvideo/centos-jdk15:latest
  variables:
    NAMESPACE: $name$
  script:
    - curl https://bintray.com/sbt/rpm/rpm |  tee /etc/yum.repos.d/bintray-sbt-rpm.repo
    - yum install -y git java-1.8.0-openjdk sbt
    - sbt "it:testOnly * -- -Ddc=eu1 -Denv=prod" -J-XX:MaxMetaspaceSize=512m
  allow_failure: true
  when: manual

ap1-canary test:
  stage: ap1
  image: tremorvideo/centos-jdk15:latest
  variables:
    NAMESPACE: $name$
  script:
    - curl https://bintray.com/sbt/rpm/rpm |  tee /etc/yum.repos.d/bintray-sbt-rpm.repo
    - yum install -y git java-1.8.0-openjdk sbt
    - sbt "it:testOnly * -- -Ddc=ap1 -Denv=canary" -J-XX:MaxMetaspaceSize=512m
  allow_failure: true
  when: manual

ap1-prod test:
  stage: ap1
  image: tremorvideo/centos-jdk15:latest
  variables:
    NAMESPACE: $name$
  script:
    - curl https://bintray.com/sbt/rpm/rpm |  tee /etc/yum.repos.d/bintray-sbt-rpm.repo
    - yum install -y git java-1.8.0-openjdk sbt
    - sbt "it:testOnly * -- -Ddc=ap1 -Denv=prod" -J-XX:MaxMetaspaceSize=512m
  allow_failure: true
  when: manual